----
---- ATTENTION CE FICHIER EST GENERE AUTOMATIQUEMENT !
----

-- ===========================================================================================
--   Application Name	:	KleeContrib.Asta 
--   Script Name		:	02_create_tables.sql
--   Description		:	Script de création des tables.
-- ===========================================================================================

/**
  * Création de la table DROIT_PROFILS
 **/
create table DROIT_PROFILS (
	DRO_CODE varchar(10) not null,
	PRO_ID int8 not null,
	constraint PK_DROIT_PROFILS primary key (DRO_CODE,PRO_ID)
);

/**
  * Création de la table DROITS
 **/
create table DROITS (
	DRO_CODE varchar(10) not null,
	DRO_LIBELLE varchar(100) not null,
	TDR_CODE varchar(10) not null,
	constraint PK_DROITS primary key (DRO_CODE)
);

/**
  * Création de la table PROFILS
 **/
create table PROFILS (
	PRO_ID int8 generated by default as identity not null,
	PRO_LIBELLE varchar(100) not null,
	PRO_DATE_CREATION date not null,
	PRO_DATE_MODIFICATION date,
	constraint PK_PROFILS primary key (PRO_ID)
);

/**
  * Création de la table TYPE_DROITS
 **/
create table TYPE_DROITS (
	TDR_CODE varchar(10) not null,
	TDR_LIBELLE varchar(100) not null,
	constraint PK_TYPE_DROITS primary key (TDR_CODE)
);

/**
  * Création de la table TYPE_UTILISATEURS
 **/
create table TYPE_UTILISATEURS (
	TUT_CODE varchar(10) not null,
	TUT_LIBELLE varchar(100) not null,
	constraint PK_TYPE_UTILISATEURS primary key (TUT_CODE)
);

/**
  * Création de la table UTILISATEURS
 **/
create table UTILISATEURS (
	UTI_ID int8 generated by default as identity not null,
	UTI_NOM varchar(100) not null,
	UTI_PRENOM varchar(100) not null,
	UTI_EMAIL varchar not null,
	UTI_DATE_NAISSANCE date,
	UTI_ADRESSE varchar(100),
	UTI_ACTIF boolean not null,
	PRO_ID int8 not null,
	TUT_CODE varchar(10) not null,
	UTI_NOM_FICHIER_PHOTO varchar(100),
	UTI_DATE_CREATION date not null,
	UTI_DATE_MODIFICATION date,
	constraint PK_UTILISATEURS primary key (UTI_ID)
);
